In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:

# # Read the Parquet file
# df = pd.read_parquet('/content/drive/MyDrive/Python practic/ETL project/yellow_tripdata_2024-01.parquet')

In [ ]:
# df.shape

(2964624, 19)

In [ ]:
# df = df.sample(frac=0.0325)

In [ ]:
# df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
716806,2,2024-01-09 17:15:40,2024-01-09 17:48:11,1.0,4.99,1.0,N,164,52,1,29.6,2.5,0.5,7.22,0.0,1.0,43.32,2.5,0.0
916076,1,2024-01-11 19:10:38,2024-01-11 19:23:40,2.0,1.50,1.0,N,246,113,1,13.5,5.0,0.5,1.00,0.0,1.0,21.00,2.5,0.0
1555835,2,2024-01-18 17:57:30,2024-01-18 18:05:05,1.0,1.38,1.0,N,236,239,1,9.3,2.5,0.5,3.16,0.0,1.0,18.96,2.5,0.0
1302592,1,2024-01-16 00:07:01,2024-01-16 00:14:04,1.0,1.10,1.0,N,170,48,2,8.6,3.5,0.5,0.00,0.0,1.0,13.60,2.5,0.0
1277623,2,2024-01-15 17:09:12,2024-01-15 17:14:32,1.0,0.65,1.0,N,43,236,2,6.5,0.0,0.5,0.00,0.0,1.0,10.50,2.5,0.0

In [ ]:
# Convert the DataFrame to a CSV file
# df.to_csv('/content/drive/MyDrive/Python practic/ETL project/yellow_tripdata_2024-01.csv', index=False)

In [ ]:
df= pd.read_csv('/content/drive/MyDrive/Python practic/ETL project/yellow_tripdata_2024-01.csv')

In [ ]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-01-09 17:15:40,2024-01-09 17:48:11,1.0,4.99,1.0,N,164,52,1,29.6,2.5,0.5,7.22,0.0,1.0,43.32,2.5,0.0
1,1,2024-01-11 19:10:38,2024-01-11 19:23:40,2.0,1.50,1.0,N,246,113,1,13.5,5.0,0.5,1.00,0.0,1.0,21.00,2.5,0.0
2,2,2024-01-18 17:57:30,2024-01-18 18:05:05,1.0,1.38,1.0,N,236,239,1,9.3,2.5,0.5,3.16,0.0,1.0,18.96,2.5,0.0
3,1,2024-01-16 00:07:01,2024-01-16 00:14:04,1.0,1.10,1.0,N,170,48,2,8.6,3.5,0.5,0.00,0.0,1.0,13.60,2.5,0.0
4,2,2024-01-15 17:09:12,2024-01-15 17:14:32,1.0,0.65,1.0,N,43,236,2,6.5,0.0,0.5,0.00,0.0,1.0,10.50,2.5,0.0

In [ ]:
df.shape

(96350, 19)

## Download csv file

In [ ]:
# from google.colab import files
# files.download('/content/drive/MyDrive/Python practic/ETL project/yellow_tripdata_2024-01.csv')

### Converting the datatype of pickup and dropoff datetime to datetime type

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96350 entries, 0 to 96349
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               96350 non-null  int64
 1   tpep_pickup_datetime   96350 non-null  object
 2   tpep_dropoff_datetime  96350 non-null  object
 3   passenger_count        91815 non-null  float64
 4   trip_distance          96350 non-null  float64
 5   RatecodeID             91815 non-null  float64
 6   store_and_fwd_flag     91815 non-null  object
 7   PULocationID           96350 non-null  int64
 8   DOLocationID           96350 non-null  int64
 9   payment_type           96350 non-null  int64
 10  fare_amount            96350 non-null  float64
 11  extra                  96350 non-null  float64
 12  mta_tax                96350 non-null  float64
 13  tip_amount             96350 non-null  float64
 14  tolls_amount           96350 non-null  float64
 15  improvement_surcharge  96350 non-null  float64
 16  total_amount           96350 non-null  float64
 17  congestion_surcharge   91815 non-null  float64
 18  Airport_fee            91815 non-null  float64
dtypes: float64(12), int64(4), object(3)
memory usage: 14.0+ MB

In [ ]:
df['tpep_pickup_datetime']= pd.to_datetime(df['tpep_pickup_datetime'])
df['tpep_dropoff_datetime']= pd.to_datetime(df['tpep_dropoff_datetime'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96350 entries, 0 to 96349
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               96350 non-null  int64
 1   tpep_pickup_datetime   96350 non-null  datetime64[ns]
 2   tpep_dropoff_datetime  96350 non-null  datetime64[ns]
 3   passenger_count        91815 non-null  float64
 4   trip_distance          96350 non-null  float64
 5   RatecodeID             91815 non-null  float64
 6   store_and_fwd_flag     91815 non-null  object
 7   PULocationID           96350 non-null  int64
 8   DOLocationID           96350 non-null  int64
 9   payment_type           96350 non-null  int64
 10  fare_amount            96350 non-null  float64
 11  extra                  96350 non-null  float64
 12  mta_tax                96350 non-null  float64
 13  tip_amount             96350 non-null  float64
 14  tolls_amount           96350 non-null  float64
 15  improvement_surcharge  96350 non-null  float64
 16  total_amount           96350 non-null  float64
 17  congestion_surcharge   91815 non-null  float64
 18  Airport_fee            91815 non-null  float64
dtypes: datetime64[ns](2), float64(12), int64(4), object(1)
memory usage: 14.0+ MB

In [ ]:
df.dropna(inplace = True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 91815 entries, 0 to 96349
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               91815 non-null  int64
 1   tpep_pickup_datetime   91815 non-null  datetime64[ns]
 2   tpep_dropoff_datetime  91815 non-null  datetime64[ns]
 3   passenger_count        91815 non-null  float64
 4   trip_distance          91815 non-null  float64
 5   RatecodeID             91815 non-null  float64
 6   store_and_fwd_flag     91815 non-null  object
 7   PULocationID           91815 non-null  int64
 8   DOLocationID           91815 non-null  int64
 9   payment_type           91815 non-null  int64
 10  fare_amount            91815 non-null  float64
 11  extra                  91815 non-null  float64
 12  mta_tax                91815 non-null  float64
 13  tip_amount             91815 non-null  float64
 14  tolls_amount           91815 non-null  float64
 15  improvement_surcharge  91815 non-null  float64
 16  total_amount           91815 non-null  float64
 17  congestion_surcharge   91815 non-null  float64
 18  Airport_fee            91815 non-null  float64
 19  trip_id                91815 non-null  int64
dtypes: datetime64[ns](2), float64(12), int64(5), object(1)
memory usage: 14.7+ MB

### Drop duplicates and set trip_id as index

In [ ]:
df = df.drop_duplicates().reset_index(drop= True)
df['trip_id'] = df.index

In [ ]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,trip_id
0,2,2024-01-09 17:15:40,2024-01-09 17:48:11,1.0,4.99,1.0,N,164,52,1,29.6,2.5,0.5,7.22,0.0,1.0,43.32,2.5,0.0,0
1,1,2024-01-11 19:10:38,2024-01-11 19:23:40,2.0,1.50,1.0,N,246,113,1,13.5,5.0,0.5,1.00,0.0,1.0,21.00,2.5,0.0,1
2,2,2024-01-18 17:57:30,2024-01-18 18:05:05,1.0,1.38,1.0,N,236,239,1,9.3,2.5,0.5,3.16,0.0,1.0,18.96,2.5,0.0,2
3,1,2024-01-16 00:07:01,2024-01-16 00:14:04,1.0,1.10,1.0,N,170,48,2,8.6,3.5,0.5,0.00,0.0,1.0,13.60,2.5,0.0,3
4,2,2024-01-15 17:09:12,2024-01-15 17:14:32,1.0,0.65,1.0,N,43,236,2,6.5,0.0,0.5,0.00,0.0,1.0,10.50,2.5,0.0,4

In [ ]:
df.shape

(91815, 20)

## Datetime_dim Table

In [ ]:
datetime_dim = df[['tpep_pickup_datetime', 'tpep_dropoff_datetime']].reset_index(drop= True)
datetime_dim['tpep_pickup_datetime'] = datetime_dim['tpep_pickup_datetime']
datetime_dim['pick_hour']= datetime_dim['tpep_pickup_datetime'].dt.hour
datetime_dim['pick_day'] = datetime_dim['tpep_pickup_datetime'].dt.day
datetime_dim['pick_month'] = datetime_dim['tpep_pickup_datetime'].dt.month
datetime_dim['pick_year'] = datetime_dim['tpep_pickup_datetime'].dt.year
datetime_dim['pick_weekday'] = datetime_dim['tpep_pickup_datetime'].dt.weekday

# droppoff
datetime_dim['tpep_dropoff_datetime'] = datetime_dim['tpep_dropoff_datetime']
datetime_dim['drop_hour']= datetime_dim['tpep_dropoff_datetime'].dt.hour
datetime_dim['drop_day'] = datetime_dim['tpep_dropoff_datetime'].dt.day
datetime_dim['drop_month'] = datetime_dim['tpep_dropoff_datetime'].dt.month
datetime_dim['drop_year'] = datetime_dim['tpep_dropoff_datetime'].dt.year
datetime_dim['drop_weekday'] = datetime_dim['tpep_dropoff_datetime'].dt.weekday

datetime_dim['datetime_id'] = datetime_dim.index

datetime_dim = datetime_dim[['datetime_id',"tpep_pickup_datetime", "pick_hour", "pick_day"
                              , 'pick_month', "pick_year", "pick_weekday", "tpep_dropoff_datetime", "drop_hour",
                             'drop_day', 'drop_month', 'drop_year', 'drop_weekday']]

datetime_dim.head()

,datetime_id,tpep_pickup_datetime,pick_hour,pick_day,pick_month,pick_year,pick_weekday,tpep_dropoff_datetime,drop_hour,drop_day,drop_month,drop_year,drop_weekday
0,0,2024-01-09 17:15:40,17,9,1,2024,1,2024-01-09 17:48:11,17,9,1,2024,1
1,1,2024-01-11 19:10:38,19,11,1,2024,3,2024-01-11 19:23:40,19,11,1,2024,3
2,2,2024-01-18 17:57:30,17,18,1,2024,3,2024-01-18 18:05:05,18,18,1,2024,3
3,3,2024-01-16 00:07:01,0,16,1,2024,1,2024-01-16 00:14:04,0,16,1,2024,1
4,4,2024-01-15 17:09:12,17,15,1,2024,0,2024-01-15 17:14:32,17,15,1,2024,0

## Passenger_count Table

In [ ]:
passenger_count_dim = df[['passenger_count']].reset_index(drop = True)
passenger_count_dim['passenger_count_id'] = passenger_count_dim.index
passenger_count_dim = passenger_count_dim[['passenger_count_id', 'passenger_count']]

#passenger_count_dim.head()

trip_distance_dim = df[['trip_distance']].reset_index(drop = True)
trip_distance_dim['trip_distance_id'] = trip_distance_dim.index
trip_distance_dim = trip_distance_dim[['trip_distance_id', 'trip_distance']]

#trip_distance_dim.head()

In [ ]:
passenger_count_dim.head()
passenger_count_dim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91815 entries, 0 to 91814
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   passenger_count_id  91815 non-null  int64
 1   passenger_count     91815 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 1.4 MB

## Rate code table

In [ ]:
rate_code_type = {
    1:"Standard rate",
    2:"JFK",
    3:"Newark",
    4:"Nassau or Westchester",
    5:"Negotiated fare",
    6:"Group ride"
}

rate_code_dim = df[["RatecodeID"]].reset_index(drop = True)
rate_code_dim['rate_code_id'] = rate_code_dim.index
rate_code_dim['rate_code_name'] = rate_code_dim['RatecodeID'].map(rate_code_type)
rate_code_dim = rate_code_dim[['rate_code_id', 'RatecodeID', 'rate_code_name']]

rate_code_dim.head()
rate_code_dim['RatecodeID'].value_counts()

RatecodeID
1.0     86637
2.0      3197
99.0      889
5.0       657
3.0       223
4.0       211
6.0         1
Name: count, dtype: int64

## Payment_type_dim Table

In [ ]:
payment_type_name = {
    1:"Credit card",
    2:"Cash",
    3:"No charge",
    4:"Dispute",
    5:"Unknown",
    6:"Voided trip"
}
payment_type_dim = df[['payment_type']].reset_index(drop=True)
payment_type_dim['payment_type_id'] = payment_type_dim.index
payment_type_dim['payment_type_name'] = payment_type_dim['payment_type'].map(payment_type_name)
payment_type_dim = payment_type_dim[['payment_type_id','payment_type','payment_type_name']]

## pickup_location and droppoff_location table

In [ ]:
pickup_location_dim = df[['pickup_longitude', 'pickup_latitude']].reset_index(drop=True)
pickup_location_dim['pickup_location_id'] = pickup_location_dim.index
pickup_location_dim = pickup_location_dim[['pickup_location_id','pickup_latitude','pickup_longitude']]


dropoff_location_dim = df[['dropoff_longitude', 'dropoff_latitude']].reset_index(drop=True)
dropoff_location_dim['dropoff_location_id'] = dropoff_location_dim.index
dropoff_location_dim = dropoff_location_dim[['dropoff_location_id','dropoff_latitude','dropoff_longitude']]

## fact_table

In [ ]:
fact_table = df.merge(passenger_count_dim, left_on='trip_id', right_on='passenger_count_id') \
             .merge(trip_distance_dim, left_on='trip_id', right_on='trip_distance_id') \
             .merge(rate_code_dim, left_on='trip_id', right_on='rate_code_id') \
             .merge(datetime_dim, left_on='trip_id', right_on='datetime_id') \
             .merge(payment_type_dim, left_on='trip_id', right_on='payment_type_id') \
             [['trip_id','VendorID', 'datetime_id', 'passenger_count_id',
               'trip_distance_id', 'rate_code_id', 'store_and_fwd_flag',
               'payment_type_id', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount',
               'improvement_surcharge', 'total_amount']]
payment_type_dim.columns

Index(['payment_type_id', 'payment_type', 'payment_type_name'], dtype='object')

In [ ]:
fact_table.columns

Index(['trip_id', 'VendorID', 'datetime_id', 'passenger_count_id',
       'trip_distance_id', 'rate_code_id', 'store_and_fwd_flag',
       'payment_type_id', 'fare_amount', 'extra', 'mta_tax', 'tip_amount',
       'tolls_amount', 'improvement_surcharge', 'total_amount'],
      dtype='object')

In [ ]:
fact_table

,trip_id,VendorID,datetime_id,passenger_count_id,trip_distance_id,rate_code_id,store_and_fwd_flag,payment_type_id,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,0,2,0,0,0,0,N,0,29.6,2.5,0.5,7.22,0.0,1.0,43.32
1,1,1,1,1,1,1,N,1,13.5,5.0,0.5,1.00,0.0,1.0,21.00
2,2,2,2,2,2,2,N,2,9.3,2.5,0.5,3.16,0.0,1.0,18.96
3,3,1,3,3,3,3,N,3,8.6,3.5,0.5,0.00,0.0,1.0,13.60
4,4,2,4,4,4,4,N,4,6.5,0.0,0.5,0.00,0.0,1.0,10.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91810,91810,2,91810,91810,91810,91810,N,91810,5.8,0.0,0.5,1.00,0.0,1.0,10.80
91811,91811,2,91811,91811,91811,91811,N,91811,7.2,0.0,0.5,2.24,0.0,1.0,13.44
91812,91812,1,91812,91812,91812,91812,N,91812,12.8,3.5,0.5,0.00,0.0,1.0,17.80
91813,91813,2,91813,91813,91813,91813,N,91813,7.9,0.0,0.5,2.38,0.0,1.0,14.28
91814,91814,2,91814,91814,91814,91814,N,91814,5.1,1.0,0.5,0.00,0.0,1.0,10.10